/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VtxScene */

#ifndef _Included_VtxScene
#define _Included_VtxScene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VtxScene
 * Method:    CCinit
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_VtxScene_CCinit
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     VtxScene
 * Method:    CCrender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VtxScene_CCrender
  (JNIEnv *, jobject);

/*
 * Class:     VtxScene
 * Method:    CCresize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_VtxScene_CCresize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     VtxScene
 * Method:    CCquit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VtxScene_CCquit
  (JNIEnv *, jobject);

/*
 * Class:     VtxScene
 * Method:    CCsetkey
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_VtxScene_CCsetkey
  (JNIEnv *, jobject, jint);

/*
 * Class:     VtxScene
 * Method:    CCsetpoint
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_VtxScene_CCsetpoint
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
