#define CS0 gl_TexCoord[0].xy
#define CS1 gl_TexCoord[0].zw
#define CS2 gl_TexCoord[1].xy
#define CS3 gl_TexCoord[1].zw
#define CS4 gl_TexCoord[2].xy
#define CS5 gl_TexCoord[2].zw
#define CS6 gl_TexCoord[3].xy
#define CS7 gl_TexCoord[3].zw
#define CS8 gl_TexCoord[4].xy
#define CS9 gl_TexCoord[4].zw
#define CS10 gl_TexCoord[5].xy
#define CS11 gl_TexCoord[5].zw
#define CS12 gl_TexCoord[6].xy
#define CS13 gl_TexCoord[6].zw
#define CS14 gl_TexCoord[7].xy
#define CS15 gl_TexCoord[7].zw
